project:
  type: book
  title: "Parallel Computing practical"
  output-dir: _book
  
book: 
  chapters: 
    - index.qmd
    - Practical.qmd
    
    
website: 
  navbar:
    left: 
      - href: Practical.qmd
        text: Home